version: '3.8'


services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://sa:password@db/mes_db  
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: